In [10]:
#iris data

#import pandas as pd
#import numpy as np

from sklearn.linear_model import LogisticRegression

from sklearn.datasets import load_iris
iris = load_iris()

from sklearn.model_selection import cross_val_score
slm = LogisticRegression(solver = "liblinear", multi_class = "auto")
scores = cross_val_score(slm, iris.data, iris.target, cv = 5)

accuracy = round(scores.mean(), 2)

file = open("output/output.csv", "w")
file.write(str(accuracy))
file.close()

In [34]:
#IQ data
import pandas as pd
import numpy as np
import scipy.stats as st
from scipy.stats import ttest_1samp

from numpy import loadtxt
data = loadtxt("res/iqdata.csv", delimiter = ",")

mean_data = round(np.mean(data), 2)
std_data = round(np.std(data), 2)

f = open("res/testcaseiq.txt", "r")
f.seek(0)

num_of_testcases = int(f.readline().rstrip("\n"))

import csv

for tcn in range(num_of_testcases):
    f2 = open("output/output" + str(tcn+1) + ".csv", mode = "w", newline = '')
    out_list = [[mean_data],[std_data]]
    lower_value = int(f.readline().rstrip('\n'))
    upper_value = int(f.readline().rstrip('\n'))
    if tcn == (num_of_testcases - 1):
        samp_filename = f.readline()
    else:
        samp_filename = f.readline().rstrip('\n')
    
    
    z_low = (lower_value - mean_data)/std_data
    z_upper = (upper_value - mean_data)/std_data
    low_prob = st.norm.cdf(z_low)
    upper_prob = st.norm.cdf(z_upper)
    prob_dist = round((upper_prob - low_prob)*100, 3)
    out_list.append([prob_dist])
    
    samp_data = loadtxt("res/" + samp_filename + ".csv", delimiter = ",")
    
    stat, pval = ttest_1samp(samp_data, mean_data)
    if pval<0.05:
        hypo = "Reject"
    else:
        hypo = "Accept"
    
    out_list.append([hypo])
    
    with f2:
        write = csv.writer(f2)
        write.writerows(out_list)
    f2.close()
    
    


In [3]:
#cars data
import pandas as pd
import numpy as np
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.model_selection import cross_val_score

cars_data = pd.read_csv("res/mtcars.csv")
#cars_data.head()


model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [4]:
#cars_data.shape

(32, 12)

In [17]:
x = cars_data.iloc[:,2:]
x = pd.DataFrame(x).to_numpy()
x

array([[  6.   , 160.   , 110.   ,   3.9  ,   2.62 ,  16.46 ,   0.   ,
          1.   ,   4.   ,   4.   ],
       [  6.   , 160.   , 110.   ,   3.9  ,   2.875,  17.02 ,   0.   ,
          1.   ,   4.   ,   4.   ],
       [  4.   , 108.   ,  93.   ,   3.85 ,   2.32 ,  18.61 ,   1.   ,
          1.   ,   4.   ,   1.   ],
       [  6.   , 258.   , 110.   ,   3.08 ,   3.215,  19.44 ,   1.   ,
          0.   ,   3.   ,   1.   ],
       [  8.   , 360.   , 175.   ,   3.15 ,   3.44 ,  17.02 ,   0.   ,
          0.   ,   3.   ,   2.   ],
       [  6.   , 225.   , 105.   ,   2.76 ,   3.46 ,  20.22 ,   1.   ,
          0.   ,   3.   ,   1.   ],
       [  8.   , 360.   , 245.   ,   3.21 ,   3.57 ,  15.84 ,   0.   ,
          0.   ,   3.   ,   4.   ],
       [  4.   , 146.7  ,  62.   ,   3.69 ,   3.19 ,  20.   ,   1.   ,
          0.   ,   4.   ,   2.   ],
       [  4.   , 140.8  ,  95.   ,   3.92 ,   3.15 ,  22.9  ,   1.   ,
          0.   ,   4.   ,   2.   ],
       [  6.   , 167.6  , 123.   ,   

In [9]:
#x.shape

(32, 10)

In [12]:
y = cars_data['mpg']
#y.head()

0    21.0
1    21.0
2    22.8
3    21.4
4    18.7
Name: mpg, dtype: float64

In [13]:
#y.shape

(32,)

In [18]:
clfr = Ridge(alpha = 1.0)
scores_r = cross_val_score(clfr, x, y, cv = 10)
scores_r

array([-11.92958659,   0.76343372,  -1.48464671,  -5.60897544,
        -1.68621967, -23.0139344 ,  -0.12390213,   0.86870249,
         0.54912748,  -0.71457497])

In [19]:
clfl = Lasso(alpha = 1.0)
scores_l = cross_val_score(clfl, x, y, cv = 10)
scores_l

array([ -8.42901101,   0.56320179,  -2.38996515,  -4.60600589,
         0.06686483, -25.27757952,  -0.12981153,   0.66802551,
         0.58391805,   0.08680842])

In [21]:
result = round((np.mean(scores_l) - np.mean(scores_r)), 2)
#result

0.35

In [25]:
import csv
out_file = open("output/output.csv", mode = 'w', newline = '')
out_file.write(str(result))
out_file.close()

In [48]:
#salinity question
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_validate
from sklearn.metrics import recall_score

sal_data = pd.read_csv("res/bottle.csv")
sal_data.head()


Cst_Cnt  Btl_Cnt       Sta_ID                                Depth_ID  \
0        1        1  054.0 056.0  19-4903CR-HY-060-0930-05400560-0000A-3   
1        1       16  054.0 056.0  19-4903CR-HY-060-0930-05400560-0152A-3   
2        2       31  052.0 075.0  19-4903CR-HY-060-2112-05200750-0010A-3   
3        2       46  052.0 075.0  19-4903CR-HY-060-2112-05200750-0250A-7   
4        2       61  052.0 075.0  19-4903CR-HY-060-2112-05200750-1203A-3   

   Depthm  T_degC  Salnty  
0       0   10.50  33.440  
1     152    8.71  33.860  
2      10    9.89  32.940  
3     250    6.32  33.943  
4    1203    3.14  34.430

In [7]:
sal_sample = sal_data.iloc[:1000, 5:]
#sal_sample.head()
#sal_sample.shape

T_degC  Salnty
0   10.50  33.440
1    8.71  33.860
2    9.89  32.940
3    6.32  33.943
4    3.14  34.430

In [11]:
#sal_sample.isnull().sum()

T_degC     5
Salnty    19
dtype: int64

In [15]:
sal_sample['T_degC'].replace(to_replace = np.NaN, value = sal_sample['T_degC'].mean(), inplace = True)
sal_sample['Salnty'].replace(to_replace = np.NaN, value = sal_sample['Salnty'].mean(), inplace = True)
#sal_sample.isnull().sum()

T_degC    0
Salnty    0
dtype: int64

In [98]:
X = sal_sample['Salnty']
Y = sal_sample['T_degC']

X = X.values.reshape(1000,1)

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state = 1)
X_train = X_train.reshape(700,1)
X_test = X_test.reshape(300,1)
train_rows = X_train.shape[0]
test_rows = X_test.shape[0]
#print(train_rows, test_rows)
#X_test.shape

In [94]:
slm = LinearRegression()
slm.fit(X_train, y_train)
coeff = [[round(slm.coef_[0], 3)]]
intc = [round(slm.intercept_,3)]

In [95]:
predicted = slm.predict(X_test)
mse = round(mean_squared_error(y_test, predicted),3)
rsquare = round(r2_score(y_test, predicted),3)
#print(mse, rsquare)

11.685 0.305


In [96]:
k_fold = KFold(n_splits = 5, random_state = 5)
scoring = ['neg_mean_squared_error']
scores = cross_validate(slm, X, Y, cv = 5, scoring = scoring)
#print(sorted(scores.keys()))
rmse = np.sqrt((-1*scores['test_neg_mean_squared_error']))
#print(scores['test_neg_mean_squared_error'])
rmse_mean = round(np.mean(rmse),3)
#rmse_mean

3.267

In [97]:
out_list1 = [[train_rows],[test_rows],[coeff],[intc]]
out_list2 = [[mse],[rsquare],[rmse_mean]]

import csv
f1 = open("output/output1.csv", mode = 'w', newline = '')
with f1:
    write = csv.writer(f1)
    write.writerows(out_list1)
f1.close()

f2 = open("output/output2.csv", mode = 'w', newline = '')
with f2:
    write = csv.writer(f2)
    write.writerows(out_list2)
f2.close()
